# mybatis
spring:
#  web:
#    cors:
#      allow-credentials: true
#      allowed-origins: "http://localhost:3000"
#      allowed-methods: GET,POST,PUT,DELETE
#      allowed-headers: "*"
  datasource:
    url: jdbc:mysql://localhost:3306/tourdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'root'
    password: '0000'
server:
  port : 8081
  address: 172.31.15.7


# JPA 사용
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/tourdb
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: 'root'
#    password: '1234'
#  jpa:
#    open-in-view: false
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: update