spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dailytour
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'root'
    password: '0000'
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update